// Code generated by "stringer -trimprefix Method_ -type Method"; DO NOT EDIT.

package mdp

import "strconv"

const _Method_name = "NILGETGETACKSETSETACKPUSHERROR"

var _Method_index = [...]uint8{0, 3, 6, 12, 15, 21, 25, 30}

func (i Method) String() string {
	if i < 0 || i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
